         
//         "pic2": "/images/image-product-2.jpg",

//         "pic3": "/images/image-product-3.jpg",
//         "pic4": "/images/image-product-4.jpg",





const data = [
 {
    "id":1,
    "pic1": "/images/image-product-1.jpg",
    "pic2": "/images/image-product-2.jpg",
    "pic3": "/images/image-product-3.jpg",
    "pic4": "/images/image-product-4.jpg",
    "title":"limited",
    "price":250,
    "type":"men",
    "discount":500,
    "text":"limited Edition",
    "text1":"Sneakers",
    "desc":"These low-profile sneakers are your perfect casual wear",
    "desc1":"companion. Featuring a durable rubber outer sole, they'll",
    "desc2":"withstand everything the weather can offer.",
},

{
    "id":2,
    "pic1": "/images/22.png",
    "pic2": "/images/23.png",
    "pic3": "/images/27.png",
    "pic4": "/images/39.jpg",
    "title":" Fall Edition",
    "price":300,
    "discount":600,
    "type":"men",
    "text":"Fall Edition",
    "text1":"Kicks",
    "desc":"These low-profile sneakers are your perfect casual wear",
    "desc1":"companion. Featuring a durable rubber outer sole, they'll",
    "desc2":"withstand everything the weather can offer.",

},

{
    "id":3,
    "pic1": "/images/38.png",
    "pic2": "/images/35.png",
    "pic3": "/images/23.png",
    "pic4": "/images/22.png",
    "title":"limited Edition",
    "price":450,
    "discount":600,
    "text":"limited Edition",
    "text1":"Joggers",
    "type":"men",
    "desc":"These low-profile sneakers are your perfect casual wear",
    "desc1":"companion. Featuring a durable rubber outer sole, they'll",
    "desc2":"withstand everything the weather can offer.",
},

{
    "id":4,
    "pic1": "/images/34.png",
    "pic2": "/images/31.png",
    "pic3": "/images/33.jpg",
    "pic4": "/images/34.png",
    "title":" Fall limited",
    "price":340,
    "discount":500,
    "text":"Fall limited",
    "type":"women",
    "text1":"Canvas",
    "desc":"These low-profile sneakers are your perfect casual wear",
    "desc1":"companion. Featuring a durable rubber outer sole, they'll",
    "desc2":"withstand everything the weather can offer.",
},
{
    "id":5,
    "pic1": "/images/25.png",
    "pic2": "/images/31.png",
    "pic3": "/images/33.png",
    "pic4": "/images/34.png",
    "title":" Fall limited",
    "price":340,
    "discount":500,
    "text":"Fall limited",
    "type":"men",
    "text1":"Canvas",
    "desc":"These low-profile sneakers are your perfect casual wear",
    "desc1":"companion. Featuring a durable rubber outer sole, they'll",
    "desc2":"withstand everything the weather can offer.",
},
{
    "id":6,
    "pic1": "/images/31.png",
    "pic2": "/images/37.png",
    "pic3": "/images/39.jpg",
    "pic4": "/images/34.png",
    "title":" Fall limited",
    "price":340,
    "discount":500,
    "text":"Fall limited",
    "text1":"Canvas",
    "type":"women",
    "desc":"These low-profile sneakers are your perfect casual wear",
    "desc1":"companion. Featuring a durable rubber outer sole, they'll",
    "desc2":"withstand everything the weather can offer.",
},
{
    "id":7,
    "pic1": "/images/29.png",
    "pic2": "/images/33.png",
    "pic3": "/images/20.jpg",
    "pic4": "/images/34.png",
    "title":" Fall limited",
    "price":340,
    "discount":500,
    "type":"men",
    "text":"Fall limited",
    "text1":"Canvas",
    "desc":"These low-profile sneakers are your perfect casual wear",
    "desc1":"companion. Featuring a durable rubber outer sole, they'll",
    "desc2":"withstand everything the weather can offer.",
},
{
    "id":8,
    "pic1": "/images/16.jpg",
    "pic2": "/images/31.png",
    "pic3": "/images/33.png",
    "pic4": "/images/16.jpg",
    "title":" Fall limited",
    "price":600,
    "discount":900,
    "type":"men",
    "text":"Fall limited",
    "text1":"Canvas",
    "desc":"These low-profile sneakers are your perfect casual wear",
    "desc1":"companion. Featuring a durable rubber outer sole, they'll",
    "desc2":"withstand everything the weather can offer.",
},

{
    "id":9,
    "pic1": "/images/39.jpg",
    "pic2": "/images/31.png",
    "pic3": "/images/33.jpg",
    "pic4": "/images/34.png",
    "title":" Fall limited",
    "price":340,
    "discount":650,
    "type":"women",
    "text":"Fall limited",
    "text1":"Canvas",
    "desc":"These low-profile sneakers are your perfect casual wear",
    "desc1":"companion. Featuring a durable rubber outer sole, they'll",
    "desc2":"withstand everything the weather can offer.",
},
{
    "id":10,
    "pic1": "/images/30.png",
    "pic2": "/images/31.png",
    "pic3": "/images/33.png",
    "pic4": "/images/34.png",
    "title":" Fall limited",
    "price":340,
    "type":"women",
    "discount":800,
    "text":"Fall limited",
    "text1":"Canvas",
    "desc":"These low-profile sneakers are your perfect casual wear",
    "desc1":"companion. Featuring a durable rubber outer sole, they'll",
    "desc2":"withstand everything the weather can offer.",
},
{
    "id":11,
    "pic1": "/images/33.png",
    "pic2": "/images/31.png",
    "pic3": "/images/33.png",
    "pic4": "/images/34.png",
    "title":" Fall limited",
    "price":440,
    "discount":700,
    "type":"women",
    "text":"Fall limited",
    "text1":"heels",
    "desc":"These low-profile sneakers are your perfect casual wear",
    "desc1":"companion. Featuring a durable rubber outer sole, they'll",
    "desc2":"withstand everything the weather can offer.",
},
{
    "id":12,
    "pic1": "/images/21.png",
    "pic2": "/images/31.png",
    "pic3": "/images/33.png",
    "pic4": "/images/34.jpg",
    "title":" Fall limited",
    "price":640,
    "discount":1200,
    "text":"Fall limited",
    "text1":"Joggers",
    "desc":"These low-profile sneakers are your perfect casual wear",
    "desc1":"companion. Featuring a durable rubber outer sole, they'll",
    "desc2":"withstand everything the weather can offer.",
},
]
export default data;